-- Comando SQL item a

SELECT C.CD_CATEGORIA, C.DS_CATEGORIA, P.CD_PRODUTO, P.DS_PRODUTO, P.VL_UNITARIO, P.TP_EMBALAGEM, P.VL_PERC_LUCRO
FROM MC_CATEGORIA_PROD C LEFT OUTER JOIN MC_PRODUTO P
ON (C.CD_CATEGORIA = P.CD_CATEGORIA)
WHERE C.TP_CATEGORIA = 'P'
ORDER BY C.DS_CATEGORIA, P.DS_PRODUTO;

-- Comando SQL item b

SELECT C.NR_CLIENTE, C.NM_CLIENTE, C.DS_EMAIL, C.NR_TELEFONE, C.NM_LOGIN, 
F.DT_NASCIMENTO, TO_CHAR(F.DT_NASCIMENTO, 'DAY') AS DIA_NASCIMENTO,  
TRUNC(MONTHS_BETWEEN(SYSDATE, F.DT_NASCIMENTO)/12) AS ANOS_VIDA, F.FL_SEXO_BIOLOGICO, F.NR_CPF 
FROM MC_CLIENTE C INNER JOIN MC_CLI_FISICA F  
ON (C.NR_CLIENTE = F.NR_CLIENTE)

-- Comando SQL item c

SELECT C.NR_CLIENTE, C.NM_CLIENTE, C.DS_EMAIL, C.NR_TELEFONE, C.NM_LOGIN, 
J.DT_FUNDACAO, TO_CHAR(J.DT_FUNDACAO, 'DAY') AS DIA_FUNDACAO,  
TRUNC(MONTHS_BETWEEN(SYSDATE, J.DT_FUNDACAO)/12) AS ANOS_VIDA_FUND, J.NR_CNPJ 
FROM MC_CLIENTE C INNER JOIN MC_CLI_JURIDICA J  
ON (C.NR_CLIENTE = J.NR_CLIENTE)

-- Comando SQL item d

SELECT V.CD_PRODUTO, P.DS_PRODUTO, V.DT_VISUALIZACAO, V.NR_HORA_VISUALIZACAO 
FROM MC_SGV_VISUALIZACAO_VIDEO V INNER JOIN MC_PRODUTO P  
ON (V.CD_PRODUTO = P.CD_PRODUTO) 
ORDER BY V.DT_VISUALIZACAO DESC, V.NR_HORA_VISUALIZACAO DESC